### ISSUE TITLE
/usr/bin/docker: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by mrserverless** [rawmind0/rancher-goagent#3]
I'm running goagent 16.7 with the volume setup correctly as per catalog: `/var/run/docker.sock:/var/run/docker.sock`

And I get the following error:

```
bash-4.3# docker                                                                
bash: /usr/bin/docker: cannot execute binary file: Exec format error

bash-4.3# uname -a                                                              
Linux gocd-agent_gocd-agent_1 4.4.10-rancher #1 SMP Fri Jun 17 17:16:24 UTC 2016
 x86_64 Linux                                                                      
```

The host is running RancherOS 4.4 with Docker 1.11.2

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

Any thoughts?

**Comment by rawmind0** [comment]
Hi @yunspace ,

Did you test this docker before doing the PR??

This is the file that is downloaded with your Dockerfile.....
-rwxr-xr-x    3 root     root         76963 Aug  3 07:04 /usr/bin/docker

Just seeing the file size, it's obvious that this is not the correct file....As you can read at docker docs, https://docs.docker.com/engine/installation/binaries/,  the procedure to install from binaries is different that the way that you are trying to do....

This is the correct file....
-rwxr-xr-x    1 root     root      15660160 Jul 28 23:59 docker/docker

I've modified the Dockerfile to proper docker client 1.12.0 install...tag 16.7.0-1

Otherwise, it doesn't work in your case...You need docker client version 1.11.2, not 1.12.0....
Why was you trying to install client version 1.12.0?? Why didn't you test the PR??

Anyway...I've make another change, to automatically detects docker server version and install the same docker client version ... tag 16.7.0-2

Updated catalog https://github.com/rawmind0/service-catalog

Best regards...

**Comment by mrserverless** [comment]
Hi @rawmind0 sorry I was still building my go pipelines when I rushed the version upgrade PRs. At the time I didn't think the docker version toggle would break things and I should have ran the `docker` command via execution terminal to make sure it was working. 

Thanks for fixing this, docker builds are working as expected. Will take more care and test every thing end to end with future PRs. Apologies once again.
